### ISSUE TITLE
有没有办法可以直接修改默认的可用次数

### ISSUE THREAD

**Issue by ElainaFanBoy** [r-earth-or/nonebot_plugin_ai_draw#1]
只能设置一个人的话有点折磨

**Comment by r-earth-or** [comment]
__init__的第101行修改第2，3个参数及103行第2，3个参数可以修改默认次数
（就是修改那两个5）
回头我把它写到config.db里去吧

**Comment by ElainaFanBoy** [comment]
> __init__的第101行修改第2，3及103行第2，3个参数可以修改默认次数
> 回头我把它写到config.db里去吧

了解，辛苦了！

**Comment by r-earth-or** [comment]
已添加至config.db
